#! bin/sh

# use a loop to copy HTML and CGI files
mkdir -p ~public_html

for file in ~/proj/html ~/proj/cgi ; do
        if [ $file -nt ~/public_html/$file ]; then 
                cp $file ~/public_html/$file
        fi
done
q3 (END) 
