#! bin/sh

# use a loop to copy HTML and CGI files
mkdir -p ~public_html

for file in ~/proj/html ~/proj/cgi ; do
        if [ COPY_ALL=1 ]; then
                cp $file ~public_html/$file
        else cp -u $file ~/public_html/$file

        fi

done
 
